### ISSUE TITLE
Spotify stream cutting out.

### ISSUE THREAD

**Issue by tstill88** [esphome/media-players#10]
Im using an M5 Echo and an M5 Atom Speaker kit and both are producing the same issue. The stream plays for around 30s-60s when you choose a song then silence, maybe 30 seconds later it resumes for 3 or 4 seconds and then stops for another 30s and so on. I had seen someone report this issue on the github page for the Raspiaudio devices, so wondered if there is something between MA and the ESP devices going wrong. When i look at the M5 ESP logs there are clearly some connection issues but i dont get why. I use a ton of ESP32 devices so i know my AP's are happy with it.

I did flash these via the web portal instead of inside ESPHome as i would do normally.

> ets Jun  8 2016 00:22:57
> 
> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 188777542, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0018,len:4
> load:0x3fff001c,len:1044
> load:0x40078000,len:10124
> load:0x40080400,len:5828
> entry 0x400806a8
> �[I][logger:243]: Log initialized
> [C][ota:461]: There have been 0 suspected unsuccessful boot attempts.
> [D][esp32.preferences:114]: Saving preferences to flash...
> [I][app:029]: Running through setup()...
> [D][binary_sensor:034]: 'M5Stack Atom Speaker Kit Button': Sending initial state OFF
> [C][fastled:012]: Setting up FastLED light...
> [C][light:036]: Setting up light 'M5Stack Atom Speaker Kit'...
> [D][light:035]: 'M5Stack Atom Speaker Kit' Setting:
> [D][light:040]:   Color mode: RGB
> [D][light:046]:   State: ON
> [D][light:050]:   Brightness: 95%
> [D][light:054]:   Color brightness: 100%
> [D][light:058]:   Red: 100%, Green: 44%, Blue: 25%
> [C][wifi:037]: Setting up WiFi...
> [D][wifi:046]: Loaded saved wifi settings: MY-WIFI
> [D][wifi:373]: Starting scan...
> [D][esp32.preferences:114]: Saving preferences to flash...
> [D][wifi:388]: Found networks:
> [I][wifi:432]: - 'MY-WIFI' (XX:XX:XX:XX:XX) [redacted]▂▄▆█
> [D][wifi:433]:     Channel: 11
> [D][wifi:434]:     RSSI: -58 dB
> [I][wifi:432]: - 'MY-WIFI' (B6:FB:E4:97:0C:BC) [redacted]▂▄▆█
> [D][wifi:433]:     Channel: 6
> [D][wifi:434]:     RSSI: -60 dB
> [D][wifi:437]: - ''[redacted] (B6:FB:E4:A6:90:72) [redacted]▂▄▆█
> [D][wifi:437]: - 'AWIFI'[redacted] (B4:FB:E4:86:90:72) [redacted]▂▄▆█
> [D][wifi:437]: - 'Inter-selecta'[redacted] (68:FF:7B:7E:11:AE) [redacted]▂▄▆█
> [D][wifi:437]: - 'AWIFI'[redacted] (B4:FB:B4:87:3C:AC) [redacted]▂▄▆█
> [D][wifi:437]: - ''[redacted] (6E:FF:7B:7E:11:AE) [redacted]▂▄▆█
> [D][wifi:437]: - 'Deco_0A64'[redacted] (6E:FF:7B:7E:0A:66) [redacted]▂▄▆█
> [D][wifi:437]: - ''[redacted] (68:FF:7B:7E:0A:66) [redacted]▂▄▆█
> [D][wifi:437]: - 'Inter-selecta'[redacted] (68:FF:7B:7E:0B:1E) [redacted]▂▄▆█
> [D][wifi:437]: - ''[redacted] (6E:FF:7B:7E:0B:1E) [redacted]▂▄▆█
> [D][wifi:437]: - 'VM2406771'[redacted] (40:0D:10:68:AE:71) [redacted]▂▄▆█
> [D][wifi:437]: - 'Virgin Media'[redacted] (52:0D:10:68:AE:71) [redacted]▂▄▆█
> [D][wifi:437]: - ''[redacted] (22:3E:A4:9F:C7:BB) [redacted]▂▄▆█
> [D][wifi:437]: - ''[redacted] (04:79:B7:FB:5F:7A) [redacted]▂▄▆█
> [D][wifi:437]: - ''[redacted] (AA:D3:43:66:D2:41) [redacted]▂▄▆█
> [D][wifi:437]: - 'MoMiKu'[redacted] (88:C3:97:C4:79:F7) [redacted]▂▄▆█
> [D][wifi:437]: - 'McKenzies clan'[redacted] (48:D3:43:66:D2:41) [redacted]▂▄▆█
> [D][wifi:437]: - 'Virgin Media'[redacted] (5A:D3:43:66:D2:41) [redacted]▂▄▆█
> [I][wifi:248]: WiFi Connecting to 'MY-WIFI'...
> [W][wifi_esp32:495]: Event: Disconnected ssid='MY-WIFI' bssid=XX:XX:XX:XX:XX[redacted] reason='Association Failed'
> [W][wifi:552]: Connecting to WiFi network failed. Are the credentials wrong?
> [W][wifi:572]: Restarting WiFi adapter...
> [I][wifi:248]: WiFi Connecting to 'MY-WIFI'...
> [I][wifi:505]: WiFi Connected!
> [C][wifi:353]:   Local MAC: 4C:75:25:A6:D3:BC
> [C][wifi:354]:   SSID: 'MY-WIFI'[redacted]
> [C][wifi:355]:   IP Address: 192.168.0.224
> [C][wifi:357]:   BSSID: XX:XX:XX:XX:XX[redacted]
> [C][wifi:358]:   Hostname: 'm5stack-atom-speaker-kit-a6d3bc'
> [C][wifi:360]:   Signal strength: -58 dB ▂▄▆█
> [C][wifi:364]:   Channel: 11
> [C][wifi:365]:   Subnet: 255.255.255.0
> [C][wifi:366]:   Gateway: 192.168.0.1
> [C][wifi:367]:   DNS1: 192.168.0.134
> [C][wifi:368]:   DNS2: 0.0.0.0
> [D][wifi:514]: Disabling AP...
> [C][ota:085]: Over-The-Air Updates:
> [C][ota:086]:   Address: m5stack-atom-speaker-kit.local:3232
> [C][api:025]: Setting up Home Assistant API server...
> [C][audio:105]: Setting up Audio...
> [I][app:062]: setup() finished successfully!
> [I][app:102]: ESPHome version 2022.6.0 compiled on Jun 16 2022, 14:50:08
> [I][app:104]: Project m5stack.atom-speaker-kit version 1.0
> [C][wifi:491]: WiFi:
> [C][wifi:353]:   Local MAC: 4C:75:25:A6:D3:BC
> [C][wifi:354]:   SSID: 'MY-WIFI'[redacted]
> [C][wifi:355]:   IP Address: 192.168.0.224
> [C][wifi:357]:   BSSID: XX:XX:XX:XX:XX[redacted]
> [C][wifi:358]:   Hostname: 'm5stack-atom-speaker-kit-a6d3bc'
> [C][wifi:360]:   Signal strength: -58 dB ▂▄▆█
> [C][wifi:364]:   Channel: 11
> [C][wifi:365]:   Subnet: 255.255.255.0
> [C][wifi:366]:   Gateway: 192.168.0.1
> [C][wifi:367]:   DNS1: 192.168.0.134
> [C][wifi:368]:   DNS2: 0.0.0.0
> [C][logger:275]: Logger:
> [C][logger:276]:   Level: DEBUG
> [C][logger:277]:   Log Baud Rate: 115200
> [C][logger:278]:   Hardware UART: UART0
> [C][gpio.binary_sensor:015]: GPIO Binary Sensor 'M5Stack Atom Speaker Kit Button'
> [C][gpio.binary_sensor:016]:   Pin: GPIO39
> [C][fastled:021]: FastLED light:
> [C][fastled:022]:   Num LEDs: 1
> [C][fastled:023]:   Max refresh rate: 400
> [C][light:104]: Light 'M5Stack Atom Speaker Kit'
> [C][light:106]:   Default Transition Length: 1.0s
> [C][light:107]:   Gamma Correct: 2.80
> [C][captive_portal:088]: Captive Portal:
> [C][mdns:084]: mDNS:
> [C][mdns:085]:   Hostname: m5stack-atom-speaker-kit-a6d3bc
> [C][ota:085]: Over-The-Air Updates:
> [C][ota:086]:   Address: m5stack-atom-speaker-kit.local:3232
> [C][api:138]: API Server:
> [C][api:139]:   Address: m5stack-atom-speaker-kit.local:6053
> [C][api:143]:   Using noise encryption: NO
> [C][improv_serial:032]: Improv Serial:
> [C][audio:131]: Audio:
> [D][api:102]: Accepted ::FFFF:C0A8:6

I also have a few errors in the HA logs

Logger: music_assistant.players.stream
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py:379
First occurred: 1:28:25 AM (52 occurrences)
Last logged: 10:42:09 PM

Simultanuous connections detected from 192.168.0.242, playback may be disturbed
Simultanuous connections detected from 192.168.0.224, playback may be disturbed
> [D][api.connection:861]: Home Assistant 2022.6.7 (::FFFF:C0A8:6): Connected successfully
> [D][media_player:059]: 'M5Stack Atom Speaker Kit' - Setting
> [D][media_player:066]:   Media URL: http://192.168.0.6:8095/e079783cf40b44bbae4720326f2e3fc9.mp3
> [I][ota:105]: Boot seems successful, resetting boot loop counter.
> [D][esp32.preferences:114]: Saving preferences to flash...
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state ON
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state OFF
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state ON
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state OFF
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state ON
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state OFF
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state ON
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state OFF
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state ON
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state OFF
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state ON
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state OFF
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state ON
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state OFF
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state ON
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state OFF
> ets Jun  8 2016 00:22:57
> 
> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 188777542, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0018,len:4
> load:0x3fff001c,len:1044
> load:0x40078000,len:10124
> load:0x40080400,len:5828
> entry 0x400806a8
> �[I][logger:243]: Log initialized
> [C][ota:461]: There have been 0 suspected unsuccessful boot attempts.
> [D][esp32.preferences:114]: Saving preferences to flash...
> [I][app:029]: Running through setup()...
> [D][binary_sensor:034]: 'M5Stack Atom Speaker Kit Button': Sending initial state OFF
> [C][fastled:012]: Setting up FastLED light...
> [C][light:036]: Setting up light 'M5Stack Atom Speaker Kit'...
> [D][light:035]: 'M5Stack Atom Speaker Kit' Setting:
> [D][light:040]:   Color mode: RGB
> [D][light:046]:   State: ON
> [D][light:050]:   Brightness: 95%
> [D][light:054]:   Color brightness: 100%
> [D][light:058]:   Red: 100%, Green: 44%, Blue: 25%
> [C][wifi:037]: Setting up WiFi...
> [D][wifi:046]: Loaded saved wifi settings: MY-WIFI
> [D][wifi:373]: Starting scan...
> [D][esp32.preferences:114]: Saving preferences to flash...
> [D][wifi:388]: Found networks:
> [I][wifi:432]: - 'MY-WIFI' [redacted]▂▄▆█
> [D][wifi:433]:     Channel: 11
> [D][wifi:434]:     RSSI: -55 dB
> [I][wifi:432]: - 'MY-WIFI' [redacted]▂▄▆█
> [D][wifi:433]:     Channel: 6
> [D][wifi:434]:     RSSI: -61 dB
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [I][wifi:248]: WiFi Connecting to 'MY-WIFI'...
> [W][wifi:557]: WiFi Unknown connection status 0
> [I][wifi:248]: WiFi Connecting to 'MY-WIFI'...
> [W][wifi:500]: Incomplete connection.
> [W][wifi_esp32:495]: Event: Disconnected ssid='MY-WIFI' bssid=[redacted] reason='Association Leave'
> [D][wifi:373]: Starting scan...
> [D][wifi:388]: Found networks:
> [I][wifi:432]: - 'MY-WIFI' [redacted]▂▄▆█
> [D][wifi:433]:     Channel: 6
> [D][wifi:434]:     RSSI: -61 dB
> [I][wifi:432]: - 'MY-WIFI' [redacted]▂▄▆█
> [D][wifi:433]:     Channel: 11
> [D][wifi:434]:     RSSI: -56 dB
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [I][wifi:248]: WiFi Connecting to 'MY-WIFI'...
> [W][wifi:500]: Incomplete connection.
> [W][wifi_esp32:495]: Event: Disconnected ssid='MY-WIFI' bssid=[redacted] reason='Association Leave'
> [I][wifi:248]: WiFi Connecting to 'MY-WIFI'...
> [W][wifi_esp32:495]: Event: Disconnected ssid='MY-WIFI' bssid=[redacted] reason='Authentication Failed'
> [W][wifi:552]: Connecting to WiFi network failed. Are the credentials wrong?
> [D][wifi:373]: Starting scan...
> [D][wifi:388]: Found networks:
> [I][wifi:432]: - 'MY-WIFI' [redacted]▂▄▆█
> [D][wifi:433]:     Channel: 11
> [D][wifi:434]:     RSSI: -52 dB
> [I][wifi:432]: - 'MY-WIFI' [redacted]▂▄▆█
> [D][wifi:433]:     Channel: 6
> [D][wifi:434]:     RSSI: -62 dB
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [D][wifi:437]: - [redacted] [redacted]▂▄▆█
> [I][wifi:248]: WiFi Connecting to 'MY-WIFI'...
> [W][wifi:500]: Incomplete connection.
> [W][wifi_esp32:495]: Event: Disconnected ssid='MY-WIFI' bssid=[redacted] reason='Association Leave'
> [I][wifi:248]: WiFi Connecting to 'MY-WIFI'...
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state ON
> [D][binary_sensor:036]: 'M5Stack Atom Speaker Kit Button': Sending state OFF
> [I][wifi:505]: WiFi Connected!
> [C][wifi:353]:   Local MAC: 4C:75:25:A6:D3:BC
> [C][wifi:354]:   SSID: [redacted]
> [C][wifi:355]:   IP Address: 192.168.0.224
> [C][wifi:357]:   BSSID: [redacted]
> [C][wifi:358]:   Hostname: 'm5stack-atom-speaker-kit-a6d3bc'
> [C][wifi:360]:   Signal strength: -53 dB ▂▄▆█
> [C][wifi:364]:   Channel: 11
> [C][wifi:365]:   Subnet: 255.255.255.0
> [C][wifi:366]:   Gateway: 192.168.0.1
> [C][wifi:367]:   DNS1: 192.168.0.134
> [C][wifi:368]:   DNS2: 0.0.0.0
> [D][wifi:514]: Disabling AP...
> [C][ota:085]: Over-The-Air Updates:
> [C][ota:086]:   Address: m5stack-atom-speaker-kit.local:3232
> [C][api:025]: Setting up Home Assistant API server...
> [C][audio:105]: Setting up Audio...
> [I][app:062]: setup() finished successfully!
> [I][app:102]: ESPHome version 2022.6.0 compiled on Jun 16 2022, 14:50:08
> [I][app:104]: Project m5stack.atom-speaker-kit version 1.0
> [C][wifi:491]: WiFi:
> [C][wifi:353]:   Local MAC: 4C:75:25:A6:D3:BC
> [C][wifi:354]:   SSID: [redacted]
> [C][wifi:355]:   IP Address: 192.168.0.224
> [C][wifi:357]:   BSSID: [redacted]
> [C][wifi:358]:   Hostname: 'm5stack-atom-speaker-kit-a6d3bc'
> [C][wifi:360]:   Signal strength: -54 dB ▂▄▆█
> [C][wifi:364]:   Channel: 11
> [C][wifi:365]:   Subnet: 255.255.255.0
> [C][wifi:366]:   Gateway: 192.168.0.1
> [C][wifi:367]:   DNS1: 192.168.0.134
> [C][wifi:368]:   DNS2: 0.0.0.0
> [C][logger:275]: Logger:
> [C][logger:276]:   Level: DEBUG
> [C][logger:277]:   Log Baud Rate: 115200
> [C][logger:278]:   Hardware UART: UART0
> [C][gpio.binary_sensor:015]: GPIO Binary Sensor 'M5Stack Atom Speaker Kit Button'
> [C][gpio.binary_sensor:016]:   Pin: GPIO39
> [C][fastled:021]: FastLED light:
> [C][fastled:022]:   Num LEDs: 1
> [C][fastled:023]:   Max refresh rate: 400
> [C][light:104]: Light 'M5Stack Atom Speaker Kit'
> [C][light:106]:   Default Transition Length: 1.0s
> [C][light:107]:   Gamma Correct: 2.80
> [C][captive_portal:088]: Captive Portal:
> [C][mdns:084]: mDNS:
> [C][mdns:085]:   Hostname: m5stack-atom-speaker-kit-a6d3bc
> [C][ota:085]: Over-The-Air Updates:
> [C][ota:086]:   Address: m5stack-atom-speaker-kit.local:3232
> [C][api:138]: API Server:
> [C][api:139]:   Address: m5stack-atom-speaker-kit.local:6053
> [C][api:143]:   Using noise encryption: NO
> [C][improv_serial:032]: Improv Serial:
> [C][audio:131]: Audio:
> [D][api:102]: Accepted ::FFFF:C0A8:6
> [D][api.connection:861]: Home Assistant 2022.6.7 (::FFFF:C0A8:6): Connected successfully

**Comment by SeByDocKy** [comment]
I think you should update to the last Music Assistant beta 2022.7.x .... it solved the same type of problem for me with the Muse
