### ISSUE TITLE
LED and button missing after adopt

### ISSUE THREAD

**Issue by cvwillegen** [esphome/media-players#12]
After adopting M5stack-atom-echo into Esphome dashboard, RGB led and Button don't work any more. After flashing the chip for the first time, they do, but adopting them makes the functionality go away.

Reproduce this issue by attaching one to your HA computer, flashing the "original" full config, and then adopting into the dashboard.

**Comment by balloob** [comment]
@jesserockz can you verify the latest YAML is up to date?

**Comment by cvwillegen** [comment]
I think I know what's going wrong... I have a cheap charger attached to the Cube. I think that the Esp can't request enough power to feed the LED. When I attach it to a smarter charger, the LED works.

Would it be a good idea to be able to specify the maximum USB current that could be supplied by the "dumb" charger? Is this possible in the code (not yet, but I could propose a change if the hardware allows it at all).

**Comment by ananyevgv** [comment]
https://github.com/zhujisheng/audio-reactive-led-strip

**Comment by ananyevgv** [comment]
esphome:
  name: ......
  platform: ESP32
  board: ......
  includes:
    - music_leds_esphome.h
    - includes/FFT.h
    - includes/ExpFilter.h
    - includes/VisualEffect.h
    - includes/gaussian_filter1d.h

light:
  - platform: fastled_clockless
#  - platform: fastled_spi
    id: LedsStrip
    chipset: NEOPIXEL
    #chipset: APA102
    pin: GPIO21
    #data_pin: GPIO21
    #clock_pin: GPIO17
    num_leds: 60
    #rgb_order: BGR
    name: "MUSIC LEDS"
    effects:
      - addressable_rainbow:
      - addressable_lambda:
          name: Scroll with Music
          update_interval: 0s
          lambda: |-
            music_leds.ShowFrame(MODE_SCROLL, &it);
      - addressable_lambda:
          name: Energy with Music
          update_interval: 0s
          lambda: |-
            music_leds.ShowFrame(MODE_ENERGY, &it);
      - addressable_lambda:
          name: Spectrum with Music
          update_interval: 0s
          lambda: |-
            music_leds.ShowFrame(MODE_SPECTRUM, &it);
