### ISSUE TITLE
muse media player not playing any song

### ISSUE THREAD

**Issue by lecrams** [esphome/media-players#29]
Hi,

Since the latest ESPhome update (2023.4.0) my muse deluxe media player is not playing any song anymore.

I have updated the media_player part in the yaml to:
i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO5

media_player:
  - platform: i2s_audio
    name: ${friendly_name}
    dac_type: external
    i2s_dout_pin: GPIO26
    mode: stereo

Compilation is okay, but If I try to stream a song nothing starts playing. 

The log from the muse media player shows:
10:48:36    [D]    [media_player:059]    
'Muse Mediaplayer' - Setting
10:48:36    [D]    [media_player:066]    
  Media URL: http://192.168.178.87:8123/media/local/01. Bachman Turner Overdrive -You Ain't Seen Nothin' Yet.mp3

**Comment by mdorchain** [comment]
Same issue here with different hardware. The board crashes and reboot.
I checked the hardware and pinout with another arduino project and it works perfectly.
It's definetly related to esphome :(

![image](https://user-images.githubusercontent.com/11390079/234647771-83f63781-caba-4602-950a-4e854f81019a.png)

**Comment by jbabio** [comment]
Same Issue here with the raspiaudio Muse Proto. Music will not play, but TTS works without issues.
May the issue be related to the version of the **ESP32-audioI2S** library as estated [here](https://github.com/esphome/issues/issues/4088#issuecomment-1476807620)?
Theoretically, different versions of the library can be selected as stated on the "Libraries" section of [ESPHome Core Configuration](https://esphome.io/components/esphome.html#esphome-libraries)

> Using \<name>=\<source> syntax, it is possible to override the version used for libraries that are automatically added by one of ESPHome’s components. This can be useful during development to make ESPHome use a custom fork of a library.

**Comment by mateuszdrab** [comment]
I'm not sure if I'm affected by the same issue; however, I just got the Muse Luxe a few days ago and I'm having issues playing back the voice assistant responses, TTS works fine as mentioned by @jbabio 
I've verified that network wise, there's no issues downloading the responses from the `/api/tts_proxy/` endpoint.

**Comment by rp3tya** [comment]
Same issue with ESP Muse Luxe.
It can play radio stations but local Home Assitant media causes a reboot (used to work before).

**Comment by jesserockz** [comment]
Hello,

We have archived this repo as the files have moved to https://github.com/esphome/firmware

If you install the latest ESPHome version and your issue still exists, please open an issue there.

Cheers,
Jesse
