### ISSUE TITLE
Raspiaudio Muse Luxe - Microphone via new I2S Audio Microphone platform

### ISSUE THREAD

**Issue by sebamigo** [esphome/media-players#33]
Is it possible to expose the microphone from the raspiaudio muse luxe via the new Audio Microphone from ESPHome?

It would be cool.
Thank you :)

**Comment by debdalerichard** [comment]
Credit to "DelusoinalAI" on Raspiaudio forum for this!

Thanks to the code by Raspiaudio, I was able to figure out the yaml for esphome.

You want to add the following:

microphone:
  - platform: i2s_audio
    id: lux_microphone
    i2s_din_pin: GPIO35

voice_assistant:
  microphone: lux_microphone
and if you want to covert the play button into a push to talk button you want to replace
media_player.toggle with voice_assistant.start and stop

    on_press:
      - voice_assistant.start:
    on_release:
      - voice_assistant.stop:
#    on_click:
#      - media_player.toggle:
This should be all you need on the esphome side of things, however the actual voice part of Home Assistant doesn’t launch until 2023.05 so you’ll have to wait a few days to actually play with it, or use the beta versions.

I haven't tested it yet as waiting for the update with home assistant!
