### ISSUE TITLE
M5 Stack Speaker Kit 

### ISSUE THREAD

**Issue by howesey2k** [esphome/media-players#41]
I noticed that the yaml file for the M5 echo now has a minimum requirement of esphome 2023.5. Since upgrading the Home Assistant add on to 2023.5, my M5 speaker kit isn't playing again properly and it's making a high pitch sound again and doesn't steam well. Please can this be fixed

**Comment by rlust** [comment]
Mine since upgrading does not work, just flashes the blue led.

**Comment by jesserockz** [comment]
Hello,

We have archived this repo as the files have moved to https://github.com/esphome/firmware

If you install the latest ESPHome version and your issue still exists, please open an issue there.

Cheers,
Jesse
