### ISSUE TITLE
Component Not Found: i2s_audio

### ISSUE THREAD

**Issue by jonherstein** [esphome/media-players#43]
Not sure what I'm doing wrong (ESPHome) but I can't get past this error when I try to install via ESPHome. Used YAML code for the proto board.

**Comment by randybb** [comment]
There was a breaking change in [2013.4.0](https://esphome.io/changelog/2023.4.0.html#i2s-media-player) which needs `i2s_audio:` component to be configured - just move the i2s port def to this.
