### ISSUE TITLE
No Audio on Muse Luxe with Home Assistant Voice Assistant

### ISSUE THREAD

**Issue by mroxso** [esphome/media-players#46]
I installed the esphome on my muse Luxe. But I don't get any voice response when using the Home Assistant Voice Assistant.
I see that the muse Luxe gets a .raw file as a response from the home assistant, but there is no sound playing.

**Comment by niahane** [comment]
Same here, I don't even see the raw file you mention.
I have authorized muse luxe to call home assistant service but not work :(

**Comment by jesserockz** [comment]
Hello,

We have archived this repo as the files have moved to https://github.com/esphome/firmware

If your issue still exists, please open an issue there.

Cheers,
Jesse
