### ISSUE TITLE
Play from SD card?

### ISSUE THREAD

**Issue by segdy** [esphome/media-players#47]
My MuseLuxe has a microSD card slot (and so do the M5's).

I would really like to store simple sound files (beeps, chimes, ...) there and play it on request ... without streaming it over Wifi every time. It doesn't work well ... and it is just wrong.

How can media files on SD card played? How to format the SD card, which format to put audio files on, which file name etc?

**Comment by jesserockz** [comment]
ESPHome doesnt support SD cards. https://github.com/esphome/feature-requests

Cheers,
Jesse

**Comment by KMTsvetanov** [comment]
how about now?
