### ISSUE TITLE
M5 Atom Echo solid blue light after update

### ISSUE THREAD

**Issue by howesey2k** [esphome/media-players#49]
After updating my Home Assistant to 2022.9 and Esp home to 8.3 I get a solid blue light when pressing the button. It no longer seems to be connected to the pipeline. In the Atoms logs, it recognises the button press. 10 or seconds later it goes from blue to off. It does not respond to any of my queries. Can someone please help.

**Comment by jesserockz** [comment]
Hello,

We have archived this repo as the files have moved to https://github.com/esphome/firmware

If your issue still exists, please open an issue there.

Cheers,
Jesse
