### ISSUE TITLE
Feature Request: Support ESP32-Audio-Kit

### ISSUE THREAD

**Issue by lein1013** [esphome/media-players#5]
Any plans to support the 
ESP32-Audio-Kit  [ESP32-Aduio-Kit ESP32-A1S ESP32 Audio Entwicklung Bord WiFi Modul Low Power Dual-core 8M PSRAM](https://www.aliexpress.com/item/3256801407357108.html) ?

**Comment by balloob** [comment]
Should be possible. If you contribute the ESPHome config we can add it to the site!

Closing this issue as this is not a place for feature requests.

**Comment by ananyevgv** [comment]
Good afternoon, managed to launch on ESP32-LyraT V4.3 
How can I lay out the configuration
