### ISSUE TITLE
Is this 8 bit audio?

### ISSUE THREAD

**Issue by elektrinis** [esphome/media-players#50]
Installed this on S5 Atom echo. Failed many times, but finally it's working.
I have connected a high end speaker instead of internal "buzzer". It's amazing how much volume this can spit out, more than enough on 50 square meter livingroom.

I have a "sensitive ear" and at moderate volumes it seemed bit off, but at really low volume levels it is now clear the audio is 8 bit?! Like, at 3% volume there is no output at all, and at 5% it is very buzz-y.

My end goal would be to install smart speakers around the house and we are certainly moving in to right direction, but here seems to be much work remaining.

**Comment by jesserockz** [comment]
Hello,

We have archived this repo as the files have moved to https://github.com/esphome/firmware

If your issue still exists, please open an issue there.

Cheers,
Jesse
