### ISSUE TITLE
raspiaudio-muse-luxe stops to play after 2min....then play few seconds more and so on ...

### ISSUE THREAD

**Issue by SeByDocKy** [esphome/media-players#7]
Well,

I flashed flawless ESPhome and installed Music Assistant. Was working great until now.... but today, trying to play some music... then 2min later ... it strops with some strange noise... pause like 30s..... then resume to play 3-4s;... then stops with the same noise... Weird.
Maybe the builtin battery is dead. Is there a way to monitor its builtin voltage ? (Maybe there is a voltage divisor bridge in the electronic to input it into one the ESP32 ADC). Is there a way to disassemble the box ? I don't want to loose the warrenty in case of broken  item.

**Comment by tstill88** [comment]
Are you still having this issue? Im getting the same but using M5 Atom devices.

**Comment by SeByDocKy** [comment]
No more .... with last beta (I guess increasing buffer size)...
